config/routes.rb
BizIn::Application.routes.draw do
  resources :products

  resources :product_categories

  resources :brands

  resources :manufacturers

  root 'application#index'

end

app/models/product_category.rb
class ProductCategory < ActiveRecord::Base
  include TenantScoped
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
  before_action :set_product_category, only: [:show, :edit, :update, :destroy]

  # GET /product_categories
  # GET /product_categories.json
  def index
    @product_categories = ProductCategory.all
  end

  # GET /product_categories/1
  # GET /product_categories/1.json
  def show
  end

  # GET /product_categories/new
  def new
    @product_category = ProductCategory.new
  end

  # GET /product_categories/1/edit
  def edit
  end

  # POST /product_categories
  # POST /product_categories.json
  def create
    @product_category = ProductCategory.new(product_category_params)

    respond_to do |format|
      if @product_category.save
        format.html { redirect_to @product_category, notice: 'Product category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @product_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_categories/1
  # PATCH/PUT /product_categories/1.json
  def update
    respond_to do |format|
      if @product_category.update(product_category_params)
        format.html { redirect_to @product_category, notice: 'Product category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @product_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_categories/1
  # DELETE /product_categories/1.json
  def destroy
    @product_category.destroy
    respond_to do |format|
      format.html { redirect_to product_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_category
      @product_category = ProductCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_category_params
      params.require(:product_category).permit(:name)
    end
end

app/helpers/product_categories_helper.rb
module ProductCategoriesHelper
end

app/views/product_categories/_form.html.erb
<%= form_for(@product_category) do |f| %>
  <% if @product_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product_category.errors.count, "error") %> prohibited this product_category from being saved:</h2>

      <ul>
      <% @product_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/product_categories/edit.html.erb
<h1>Editing product_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @product_category %> |
<%= link_to 'Back', product_categories_path %>

app/views/product_categories/index.html.erb
<h1>Listing product_categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @product_categories.each do |product_category| %>
      <tr>
        <td><%= product_category.name %></td>
        <td><%= link_to 'Show', product_category %></td>
        <td><%= link_to 'Edit', edit_product_category_path(product_category) %></td>
        <td><%= link_to 'Destroy', product_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product category', new_product_category_path %>

app/views/product_categories/new.html.erb
<h1>New product_category</h1>

<%= render 'form' %>

<%= link_to 'Back', product_categories_path %>

app/views/product_categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product_category.name %>
</p>

<%= link_to 'Edit', edit_product_category_path(@product_category) %> |
<%= link_to 'Back', product_categories_path %>